pool:
  name: Azure Pipelines

parameters:
- name: serviceConnectionName
  type: string
  default: ''

- name: solution
  type: string
  default: ''

trigger: none

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    echo "##vso[task.setvariable variable=branch]("$(Build.SourceBranch)".Split('/'))[-1]"
  displayName: '📌Get Branch Name'

- powershell: |
    git config --global user.email ""
    git config --global user.name ""
    git fetch
    git branch "$(branch)"
    git fetch
    git checkout "$(branch)"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: '🐈Git fetch, branch and checkout'

- template: templates\install-pac.yml
  displayName: '⬇️Power Platform Tool & PAC CLI Installer'

- task: PowerPlatformSetConnectionVariables@2
  name: connection
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: '${{parameters.serviceConnectionName}}'
  displayName: '🔐Set Connection Variables'

- powershell: |
      . '$(System.DefaultWorkingDirectory)/powershell/functions.ps1"
      Invoke-Clone-Or-Sync-Solution "$(pacPath)" "$(connection.BuildTools.TenantId)" "$(connection.BuildTools.ApplicationId)" "$(connectionVariables.BuildTools.ClientSecret)" "$(connectionVariables.BuildTools.Url)" '$(System.DefaultWorkingDirectory)/solution/' "${{parameters.solution}}"
  displayName: '🔵pac - Clone or Sync Solution'

- powershell: |
    . '$(System.DefaultWorkingDirectory)/json.ps1'
    JsonHelperMap -tgt '_' -json '$(System.DefaultWorkingDirectory)/solution/$(solution)/Workflows' -jsonConfig '_' -fn '___' -p 'defaultValue' -sp 'triggers,actions' -a 'Erase'
  displayName: '⚡Workflows: Erase Default Value'

- powershell: |
    git add --all
    git commit -m "Solution $(solution)"
    git push origin main
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: '🐈Git add, commit and push'