pool:
  name: Azure Pipelines

trigger: none

steps:
- checkout: self
  persistCredentials: true

- powershell: |
  git clone https://github.com/VinnyDyn/ALMFramework
  git commit -m "init"
  git push -u origin main
workingDirectory: '$(System.DefaultWorkingDirectory)'
displayName: 'Git Init'