# Copy Paste on Power Automate
# Set:
# > user.email
# > user.name
# > templateSource

pool:
  name: 'Azure Pipelines'

trigger: none

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    git config --global user.email ""
    git config --global user.name ""
    git checkout main
    $templateSource = "https://github.com/VinnyDyn/ALMFramework/archive/refs/heads/main.zip"
    $templateZip = "$(System.DefaultWorkingDirectory)\template.zip"
    Invoke-WebRequest -Uri $templateSource -OutFile $templateZip
    Expand-Archive -LiteralPath $templateZip -DestinationPath '$(System.DefaultWorkingDirectory)'
    $templateFolder = Get-ChildItem -Path '$(System.DefaultWorkingDirectory)' -Directory | Select-Object -First 1
    Get-ChildItem -Path $templateFolder | Move-Item -Destination '$(System.DefaultWorkingDirectory)'
    Remove-Item -Path $templateZip
    Remove-Item -Path $templateFolder
    git add --all
    git commit -m "init"
    xgit push -u origin main
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Git Template Sync'