# Copy Paste on Power Automate
# Set:
# > user.email
# > user.name
# > templateSource

pool:
  name: 'Azure Pipelines'

trigger: none

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    git config --global user.email "@{outputs('Get_Organization')?['body/vhlb_git_useremail']}"
    git config --global user.name "@{outputs('Get_Organization')?['body/vhlb_git_username']}"
    git checkout main
    Write-Host "Start download template"
    $templateSource = "https://github.com/VinnyDyn/ALMFramework/archive/refs/heads/main.zip"
    $templateZip = "$(System.DefaultWorkingDirectory)\template.zip"
    Invoke-WebRequest -Uri $templateSource -OutFile $templateZip
    Expand-Archive -LiteralPath $templateZip -DestinationPath '$(System.DefaultWorkingDirectory)'
    $templateFolder = Get-ChildItem -Path '$(System.DefaultWorkingDirectory)' -Directory | Select-Object -First 1
    Get-ChildItem -Path $templateFolder | Move-Item -Destination '$(System.DefaultWorkingDirectory)'
    Write-Host "End download template"
    Write-Host "Start build.yaml"
    $buildYamlFilePath = "$(System.DefaultWorkingDirectory)\build.yaml"
    $buildYamlContent = Get-Content -Path $buildYamlFilePath -Raw
    $buildYamlContent = $buildYamlContent -replace "#SERVICECONNECTIONNAME#", "@{outputs('Get_Connection')?['body/vhlb_name']}"
    $buildYamlContent = $buildYamlContent -replace "#SOLUTION#", "@{triggerOutputs()?['body/vhlb_name']}"
    $buildYamlContent = $buildYamlContent -replace "#VERSION#", "1.0.0"
    $buildYamlContent = $buildYamlContent -replace "#GITNAME#", "@{outputs('Get_Organization')?['body/vhlb_git_username']}"
    $buildYamlContent = $buildYamlContent -replace "#GITEMAIL#", "@{outputs('Get_Organization')?['body/vhlb_git_useremail']}"
    Set-Content -Path $buildYamlFilePath -Value $buildYamlContent
    Write-Host "End build.yaml"
    Remove-Item -Path $templateZip -Force
    Remove-Item -Path $templateFolder -Recurse -Force
    git add --all
    git commit -m "init"
    git push -u origin main
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Git Template Sync'